PROJECT_NAME = "Pecunia"
PROJECT_VERSION = "v1.0.4"
PROJECT_BUILD_TIME = "2025-04-22 21:36:52"

DATA_FILE = "./data/pecunia.json"

PROJECT_INFO = (f"""
{PROJECT_NAME}
Version:{PROJECT_VERSION}
Build Time:{PROJECT_BUILD_TIME}
""")
