PROJECT_NAME = "Pecunia"
PROJECT_VERSION = "v1.1.0"
PROJECT_BUILD_TIME = "2025-05-03 19:52:14"

DATA_FILE = "./data/pecunia.json"

PROJECT_INFO = (f"""
{PROJECT_NAME}
Version:{PROJECT_VERSION}
Build Time:{PROJECT_BUILD_TIME}
""")
