PROJECT_NAME = "Pecunia"
PROJECT_VERSION = "v1.2.0"
PROJECT_BUILD_TIME = "2025-06-01 09:50:43"

DATA_FILE = "./data/pecunia.json"

PROJECT_INFO = (f"""
{PROJECT_NAME}
Version:{PROJECT_VERSION}
Build Time:{PROJECT_BUILD_TIME}
""")
